### ISSUE TITLE
Latest version (7/21) fails to load TPUs and other errors

### ISSUE THREAD

**Issue by NickM-27** [ich777/unraid-coral-driver#3]
Just updated to 7/21 through the Unraid store and the plugin appeared with a default green icon and the plugin page itself showed another tab "plugin errors". 

I uninstalled and manually installed from an old commit, but it seems the latest version has something wrong.

**Comment by ich777** [comment]
I will check that shortly.

**Comment by ich777** [comment]
@NickM-27 can you maybe send over your diagnostics please?

**Comment by NickM-27** [comment]
![Screen Shot 2022-07-21 at 09 00 56 AM](https://user-images.githubusercontent.com/14866235/180246826-755b8768-c12d-4765-b282-56daec3bfa0d.png)

**Comment by NickM-27** [comment]
This happens first and puts everything in a weird state. Let me know what you want me to do then I will do it and get diagnostics if desired

**Comment by ich777** [comment]
Have you yet tried to reboot once after you've uninstalled it from the Plugins-Removed tab?

**Comment by NickM-27** [comment]
The steps I took previously were:
1. Got this error
2. Uninstalled and reinstalled from store
3. Rebooted
4. Found the plugin had a generic green puzzle icon and the "Coral Drivers" was not under Settings in Unraid
5. Uninstall and reinstalled older version where everything was fine

Updating again caused the same thing to happen. I can try uninstalling and then reboot to install?

**Comment by ich777** [comment]
Unfortunately I can't reproduce this on my server...
The plugin downloads just fine.

Which one did you install?

**Comment by NickM-27** [comment]
I went to fa078f8d88e89c217758131c6ce43b5cf1c7b1da and installed manually from the `.plg`

I see after the last screenshot I sent

![Screen Shot 2022-07-21 at 09 15 54 AM](https://user-images.githubusercontent.com/14866235/180250352-9951f097-f3ae-4852-b5b2-1873a479a517.png)

Pressing update again leads to

![Screen Shot 2022-07-21 at 09 16 16 AM](https://user-images.githubusercontent.com/14866235/180250430-435327dd-d737-413c-9b9e-8d0470dcaca0.png)
 
and then the plugin is missing from the settings page in Unraid entirely

**Comment by ich777** [comment]
Should be fixed, now. Try to redownload it again please and remove it of course first.

**Comment by NickM-27** [comment]
Yep, had to do a remove and reboot but fresh download works great, thank you!

**Comment by NickM-27** [comment]
Side note, is there a good way to permantently change the throttle and shutdown temperatures, or is the best way just to create a script that runs on array start that updates the apex_y files?

**Comment by ich777** [comment]
@NickM-27 please remove it and redownload it once more, I've pushed a change shortly after I posted that it's fixed, I forgot two things to change while modifying the plugin... Sorry about that...
Maybe try to reboot once more and see if the plugin is loaded successful.

Sure thing edit the file `/boot/config/plugins/coral-driver/settings.cfg` and edit entry `shutdowntemp0` but you can also disable it by `changing shutdown_en0` to `0`
With the latest update this will change all connected PCI based Coral devices.

**Comment by NickM-27** [comment]
The plugin itself loaded alright and looks normal, however opening it still shows `No Corals Detected` but I can see them in the `Tools -> System Devices`

**Comment by ich777** [comment]
I have pushed another update which should fix this. ;)

**Comment by NickM-27** [comment]
Is it still under the `2022.07.21a` version?

**Comment by NickM-27** [comment]
Uninstalling and reinstalling has them appear again

**Comment by ich777** [comment]
2022.07.21b

**Comment by NickM-27** [comment]
Ah I see, has it been published? Perhaps my store hasn't updated yet

**Comment by ich777** [comment]
Currently rebooting my test server.
That's actually a DNS caching thing, you have to wait for about 5 mins or so and then search again for updates.

**Comment by NickM-27** [comment]
Yep there it is, rebooted and now it looks good. Thanks!

**Comment by ich777** [comment]
If you install it from scratch from the CA App it will work but I've found another thing that needs to be fixed, nothing for you to worry about.

**Comment by NickM-27** [comment]
Thank you for the quick response
